USE master;
GO

CREATE DATABASE QLSV ON 
PRIMARY (
    NAME = QLHH_data,
    FILENAME = 'F:\projects\SQLServerLog\QLSV\QLSV.mdf',
    SIZE = 50MB,
    MAXSIZE = 200MB,
    FILEGROWTH = 10MB
)
LOG ON (
    NAME = QLHH_log,
    FILENAME = 'F:\projects\SQLServerLog\QLSV\QLSV.ldf',
    SIZE = 10MB,
    FILEGROWTH = 5MB
);
GO

USE QLSV
GO

CREATE TABLE KHOA
(
	MaKH		CHAR(2),
	TenKH		NVARCHAR(50),
	CONSTRAINT pk_KHOA PRIMARY KEY(MaKH)
)

CREATE TABLE MON
(
	MaMH		CHAR(2),
	TenMH		NVARCHAR(50),
	Sotiet		INT,
	CONSTRAINT pk_MON PRIMARY KEY(MaMH)
)

CREATE TABLE SINHVIEN
(	
	MaSV		CHAR(2),
	HoSV		NVARCHAR(30),
	TenSV		NVARCHAR(20),
	Phai		BIT,
	Ngaysinh	DATETIME,
	NoiSinh		NVARCHAR(50),
	MaKH		CHAR(2),
	Hocbong		REAL,
	CONSTRAINT pk_SINHVIEN PRIMARY KEY(MaSV),
	CONSTRAINT fk_SINHVIEN_MaKH
				FOREIGN KEY(MaKH)
				REFERENCES KHOA(MaKH)
)

CREATE TABLE KETQUA
(
	MaSV		CHAR(2),
	MaMH		CHAR(2),
	Diem		INT,
	CONSTRAINT pk_KETQUA PRIMARY KEY(MaSV, MaMH),
	CONSTRAINT fk_KETQUA_MaSV
				FOREIGN KEY(MaSV)
				REFERENCES SINHVIEN(MaSV),
	CONSTRAINT fk_KETQUA_MaMH
				FOREIGN KEY(MaMH)
				REFERENCES MON(MaMH)
)
