/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testnative_Main */

#ifndef _Included_testnative_Main
#define _Included_testnative_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testnative_Main
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_testnative_Main_square
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
